apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: alisharb/app1:TAG_PLACEHOLDER  # This will be replaced by Jenkins
          ports:
            - containerPort: 80
